name: energy-estimation
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=24.2
  - setuptools=75.1.0
  - wheel=0.44.0
  - cmake
  - pip:
      - annotated-types==0.7.0
      - arrow==1.4.0
      - attrs==25.3.0
      - authlib==1.3.2
      - backports-zoneinfo==0.2.1
      - certifi==2026.2.25
      - cffi==1.17.1
      - charset-normalizer==3.4.6
      - click==8.1.8
      - codecarbon==3.2.3
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cryptography==46.0.5
      - cycler==0.12.1
      - flatbuffers==25.12.19
      - fonttools==4.57.0
      - humanfriendly==10.0
      - idna==3.11
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - jsonlines==4.0.0
      - kiwisolver==1.4.7
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - mdurl==0.1.2
      - mpmath==1.3.0
      - networkx==3.1
      - nn-meter==2.0
      - numpy==1.24.4
      - nvidia-ml-py==13.595.45
      - onnx==1.13.1
      - onnx-simplifier==0.5.0
      - onnxruntime==1.19.2
      - onnxsim==0.5.0
      - packaging==26.0
      - pandas==2.0.3
      - pillow==10.4.0
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.52
      - protobuf==3.20.3
      - psutil==6.0.0
      - py-cpuinfo==9.0.0
      - pycountry==24.6.1
      - pycparser==2.23
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.2
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pytz==2026.1.post1
      - pyyaml==6.0.3
      - questionary==2.1.0
      - rapidfuzz==3.9.7
      - requests==2.32.4
      - rich==14.3.3
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - shellingham==1.5.4
      - six==1.17.0
      - sympy==1.13.3
      - threadpoolctl==3.5.0
      - torch==1.9.0
      - torchvision==0.10.0
      - tqdm==4.67.3
      - typer==0.20.1
      - typing-extensions==4.13.2
      - tzdata==2025.3
      - urllib3==2.2.3
      - wcwidth==0.6.0
      - zipp==3.20.2
